#!/bin/bash

for d in `find . -type d -name ".git"`
do
    git_dir=`realpath $d`
    diff=`git --git-dir=$git_dir log origin/master..HEAD --oneline 2>/dev/null`
    if [ "$diff" != "" ] ; then
        echo $git_dir
    fi
done
